server:
  port: 8082
spring:
  profiles:
    include: oauth, real-db
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    timeout: 600